CREATE TABLE IF NOT EXISTS event_register
                    (EVENT_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     EVENT_KEY INT NOT NULL,
                     EVENT VARCHAR(255) NOT NULL,
                     event_time BIGINT NOT NULL);
